server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/employees/**
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumers/**