version: '3'
# https://github.com/keycloak/keycloak-containers/tree/master/docker-compose-examples

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      restart: always
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports: ['5432:5432'] # the HTTP endpoint
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
